### ISSUE TITLE
Broken on newest react for me

### ISSUE THREAD

**Issue by wrightwriter** [maisano/react-router-transition#102]
throws the following error
```
You should not use <Route> or withRouter() outside a <Router>
```
when using     AnimatedSwitch

**Comment by idmadj** [comment]
Hey @wrightwriter, can you try switching your project to 'idmadj/react-router-transition#fix-102' and see if it fixes your issue? Looks like react-router-transition uses a now deprecated way of importing the react-router classes.

**Comment by ogostus** [comment]
> Hey @wrightwriter, can you try switching your project to 'idmadj/react-router-transition#fix-102' and see if it fixes your issue? Looks like react-router-transition uses a now deprecated way of importing the react-router classes.

have same issue and your fix is not working

**Comment by Vija02** [comment]
It seems like the context changes on`react-router v4.4.0` forces you to import the code from the same place. 

I got it working by changing `react-router-dom` into a peerDependency in addition with @idmadj's changes.

I'll whip up a PR when there's time
