### ISSUE TITLE
Slide animation

### ISSUE THREAD

**Issue by nats12** [maisano/react-router-transition#105]
Hi, not an issue as such but is there a slide as well as a spring? For a smoother transition between pages. Thanks.

**Comment by maisano** [comment]
hi @nats12! all transitions powered by `react-router-transition` are ultimately powered by `react-motion`'s spring physics. so, unfortunately, everything is spring-based. there are a handful of other libraries that support more types of animations for mounting/unmounting transitions though (e.g. popmotion pose).
