### ISSUE TITLE
AnimatedSwitch throws error if maximum update depth is exceeded within a HOC

### ISSUE THREAD

**Issue by slavkobojanic** [maisano/react-router-transition#107]
In my particular case i'm using the AnimatedSwitch within a HOC router so that i've got the ability to do public/private routes. For some context, within these public/private routes it'll check if the user is authenticated if they are, all is well and works fine, but if they are not then it'll redirect them to some arbitrary route which is where the maximum update depth is exceeded.

Not a great amount of context is provided in the console but I can certainly confirm that it's to do with the redirect (as it didn't have issues with some other arbitrary element) and also that it works fine with the Switch provided by react-router itself. 

![image](https://user-images.githubusercontent.com/914906/57570756-cdc1ac80-7448-11e9-858e-e71bc5b70bc0.png)

Here's the error log, let me know if you need any more context or anything :)

**Comment by Glavin001** [comment]
@slavkobojanic : Same here. Did you find a workaround?

**Comment by slavkobojanic** [comment]
@Glavin001 Unfortunately not - I was not able to find a solution to this and it seems that the maintainer is not actively developing this.
