### ISSUE TITLE
componentWillReceiveProps is going to be deprecated

### ISSUE THREAD

**Issue by nightspirit** [maisano/react-router-transition#109]
React is going to deprecate componentWillReceiveProps in version 17 which will affect `AnimatedSwitch`.

Do you have any plan to fix it?

I am not sure if you move the affected code into "componentDidUpdate" will cause any other trouble. There is another way "getDerivedStateFromProps" but that will force people to have react 16.3.0+ as peer dependency.

**Comment by iMerica** [comment]
The author of this project appears to be MIA. Feel free to use my fork in the interim.

`yarn add iMerica/react-router-transition`.

**Comment by maisano** [comment]
I plan on merging #110 fairly soon. While it is a bigger departure from marking this lifecycle method with `UNSAFE_`, it seemed like a good opportunity to revisit this package and update it to use hooks.

**Comment by maisano** [comment]
This has been solved by #110 – let me know if you have any other concerns.
