### ISSUE TITLE
Warning: componentWillReceiveProps

### ISSUE THREAD

**Issue by xavruss** [maisano/react-router-transition#121]
react-dom.development.js:67 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: TransitionMotion

**Comment by maisano** [comment]
Which version of `react-router-transition` are you using? `TransitionMotion` is from a transitive dependency, `react-motion`–the latest version should contain the [prefixed lifecycle method name](https://github.com/chenglou/react-motion/blob/9e3ce95bacaa9a1b259f969870a21c727232cc68/src/TransitionMotion.js#L579).

**Comment by xavruss** [comment]
my version is "react-router-transition": "^ 2.1.0", I am also surprised,
my version of react is 17, and to install router-transition I used the --legacy-peer-deps flag I guess that was it. sorry for the late reply and my bad english
