### ISSUE TITLE
change pathname prop to key

### ISSUE THREAD

**Issue by maisano** [maisano/react-router-transition#18]
people get (very understandbly) confused about the pathname prop. it should probably be changed to "key".

**Comment by leonaves** [comment]
I don't think there's necessarily a problem with the word "pathname", it helps to tangibly tie it to react-router, this is made for "route" transitions after all, I think "key" is just further abstract.

**Comment by leonaves** [comment]
What about "route"? "Pathname" kind of implies the whole path, as well as it having the same name as the property that holds the whole path, where "route" isn't necessarily the entire path. That along with readme changes I think would really help clarify things.

**Comment by jacobangel** [comment]
How bad would it be to just have a v4 specific `<SwitchTransition>` component? Too closely bound? 

aka: 
 ```
 <Route render={({location, history, match}) => (
     <SwitchTransition 
        location={location}        
        key={location.key}
        atEnter={{ opacity: 0 }}
        atLeave={{ opacity: 0 }}
        atActive={{ opacity: 1 }}
      >
          <Route exact path="/" component={Home} />
          <Route exact path="/about/" component={About}/>
      </SwitchTransition>    
  )} />
```

**Comment by jacobangel** [comment]
Derp, just saw the date on this.

**Comment by maisano** [comment]
this is already done, i just haven't finalized it and made new docs for it.
