### ISSUE TITLE
Strongly recommend "Reading" about React Router v4 or strongly recommend using that instead of this module?

### ISSUE THREAD

**Issue by iDVB** [maisano/react-router-transition#22]
Sorry I was a bit confused as you your router v4 ref and the beginning of the readme. 

We're really struggling with v2 and trying to get very granular page transitions across our site. 
For instance, we have two elements on a single page animating in completely different directions and transforms. (GSAP)

The code is pretty kludgy and we've gotten to the point we're dieing to try something more reliable.

Does this mean we should look at pivoting to v4...... or rather to using this component? Just curious as to what you think based on the fact that you seem to know both fairly well.

**Comment by maisano** [comment]
hi @iDVB! here are some sentiments of mine on this project and react-router:

whether or not to use `react-router-transition` depends on how much lock-in you have with v2. v4 of `react-router` is much more flexible and affords more granularity in declaring routes. it does have some drawbacks (possible route/design fragmentation, more architectural onus on users, etc.) but overall it seems like a great direction for the library.

honestly, `RouteTransition`, is not coupled `react-router` in any way whatsoever. the only inherent thing typing it to router is the `pathname` prop, which should technically be called `key`. in actuality the library a thin abstraction on top of `TransitionMotion` in an effort to make the api easier to work with–`react-motion` is great, as is its api, but the learning curve is steep.

last, and perhaps more weird, i don't use this library myself. i wrote the code for it when `react-motion` was first announced, as we were experimenting with `react-router` where i work and needed route transitions. that project was abandoned, but i posted a gist of `RouteTransition` to share the code with folks who wanted to try motion in the router. it was easier/more self-documenting to just turn it into a lib and publish it than to field questions in the gist, so i made this.

all that said, i would try using it. it might work for you. it might not. it should definitely help you prototype what you're looking for, and maybe you'll find it works for you. maybe you'll find that you need more control and just want to use `react-motion` directly.
