### ISSUE TITLE
have option to use css transitions instead of react motion

### ISSUE THREAD

**Issue by hoomersinpsom** [maisano/react-router-transition#24]
to gain more control on page transition elements, i think will help a lopt to have the o option to work like the ReactCSSTransitionGroup component https://facebook.github.io/react/docs/animation.html or the ngAnimate in the view directive on angular

**Comment by maisano** [comment]
@hoomersinpsom thanks for the feedback! while it is possible to animate route transitions with `CSSTransitionGroup`, the main focus of this project has been in providing an abstraction on top of react-motion. the transition group api is a lot easier to grok and prototype with, so i like leaving the focus of this project on react-motion.
