### ISSUE TITLE
`NaN` is an invalid value

### ISSUE THREAD

**Issue by zackargyle** [maisano/react-router-transition#25]
Getting the following error.
`Warning: `NaN` is an invalid value for the `opacity` css style property.`

This is what the code looks like
```
<RouteTransition pathname={location.pathname} {...presets.slideLeft}>
    {children}
</RouteTransition>
```

Have you seen this before?

**Comment by maisano** [comment]
hi @zackargyle–i have not seen this before, though i have a hunch that one of the opacity values passed into react-motion's `TransitionMotion` are not numerical, thus tweening results in `NaN`. so i can repro, which version of react-motion do you have installed, `0.4.5`?

**Comment by maisano** [comment]
@zackargyle any luck on this issue on your end?

**Comment by maisano** [comment]
closing this. feel free to reopen later.
