### ISSUE TITLE
A big lag while transitioning on Android

### ISSUE THREAD

**Issue by floviolleau** [maisano/react-router-transition#27]
Hi,

I'm facing to a big big lag on a webapp on Android 6.0.1 with an old Android System Webview.

My RouteTransition configuration is like this:
```
<RouteTransition
          className="transition-wrapper"
          pathname={this.props.location.pathname}
          atEnter={{ opacity: 0 }}
          atLeave={{ opacity: 0 }}
          atActive={{ opacity: 1 }}>
          <div className="wrapper">{childrenWithProps}</div>
</RouteTransition>
```
Of course:
```
<div className="wrapper">{childrenWithProps}</div>
```
is in position absolute.

While transitioning, the computation of the opacity is extremely slow on my wrapper div and very strange... :
![2016-11-22_19-24-58](https://cloud.githubusercontent.com/assets/5442973/20536638/0fefc0c6-b0ea-11e6-87f1-94667c6c1545.gif)

It could be endless or took lot of time.

If anyone could help me on that hot topic for me?

Thanks.

**Comment by maisano** [comment]
hi @floviolleau!

one thing i noticed–you can avoid the `<div className="wrapper">{childrenWithProps}</div>` as this library provides that for free (it's opt-out). to make the wrapper targetable, just pass in a `className` prop to `RouteTransition` itself. if you require a parent container, wrap `RouteTransition` itself.

regarding perf/interpolation–that all comes from `react-motion`, although this is kinda sus. i guess i would recommend trying two things to see if we can get the transition to complete:

1. get rid of the inner div.
2. check which version of `react-motion` you're on. looks like they're at `0.4.5`, though there's nothing listed in the changelog for that version. perhaps try `0.4.2` or some other prior to latest.

**Comment by floviolleau** [comment]
Hi, 

Thanks for your quick reply.

From the tests **_independently_** I did:
1. I removed the extra div and at the same time the `position: absolute` on that div
=> works but while transitioning, I'm facing to a quick blank page which is not expected.
![2016-11-23_10-59-10](https://cloud.githubusercontent.com/assets/5442973/20559925/26521692-b177-11e6-8f04-fa8b3131abcd.gif)
2. Or I just removed the `position: absolute` on the `<div className="wrapper">{childrenWithProps}</div>` and kept this div
=> I'm facing exactly at the same problem like 1.
3. Or I added: 
```
.transition-wrapper {
  position: relative;
  > div {
    height: 100vh;
    width: 100vw;
    transform: translateZ(0);
    transform-style: flat;
    backface-visibility: hidden; // with or without, we have the same effect
  }
}
```
and kept `position: absolute` on my `wrapper` div
=> I'm facing exactly at the same problem like 1 and moreover, I have a problem of z-index with my modals and their overlays due to the `transform: translateZ(0)` property that forces the browser to create a new layer and send rendering to the GPU.

I checked the `react-motion` version and this package is installed with react-router-transition. `react-motion` is in version 0.4.5 in my project. I will try later to downgrade it.

**Comment by floviolleau** [comment]
Downgrade react-motion to older version does not change anything but upgrade Android System webview fix it...

My customer says:
> We must solve it even for the current webview problem.
> We cannot rely on people to know they need to upgrade it (webview).
> This is extremely important.

**Comment by maisano** [comment]
@floviolleau in the 3rd option you enumerated: you would need to add `position: absolute` to the `> div` rule–otherwise the routes will not be positioned on top of one another (i.e. the routes will be stacked and you will transition to nothing until the new route suddenly pops in). try this?

**Comment by floviolleau** [comment]
@maisano Thanks for all your ideas but what you suggested does not work.

**Comment by floviolleau** [comment]
Finally I used this configuration:
```
<RouteTransition
          className="transition-wrapper"
          pathname={this.props.location.pathname}
          atEnter={{ opacity: 0 }}
          atLeave={{ opacity: 1 }}
          atActive={{ opacity: 1 }}>
          <div className="wrapper">{childrenWithProps}</div>
</RouteTransition>
```
instead of:
```
<RouteTransition
          className="transition-wrapper"
          pathname={this.props.location.pathname}
          atEnter={{ opacity: 0 }}
          atLeave={{ opacity: 0 }}
          atActive={{ opacity: 1 }}>
          <div className="wrapper">{childrenWithProps}</div>
</RouteTransition>
```

This is not the behavior as expected but almost the transition effect expected. It's very much faster than before.

The problem I think, it's that on pretty low devices with an old Android System Webview, doing a double inverted opacity rendering get the device very slow. I hope it will help someone in the future.

As a reminder, with a Android System Webview app up-to-date (11/25/2016) you normaly not face to this probem.

**Comment by maisano** [comment]
@floviolleau thanks for following up with this! sorry i couldn't be more help.
