### ISSUE TITLE
Prevent animation at app startup

### ISSUE THREAD

**Issue by Unforgiven-wanda** [maisano/react-router-transition#28]
Hello,
I would like to avoid having the router animation kick in at initial app load, instead having it only at route change. Do you support this scenario?
Thank you.

**Comment by maisano** [comment]
hi @Unforgiven-wanda!

assuming you're _always_ rendering the `RouteTransition`, there's a prop for that–`runOnMount`. if you set this to `false` then the transitions will only occur when the location changes.
