### ISSUE TITLE
Would be nice to include translateY in the transitions.

### ISSUE THREAD

**Issue by ananescu** [maisano/react-router-transition#29]
I was having some problems with a modal that I wanted to transition from the bottom up. I tried using translateY as you used translateX in the demos and it didn't work.

**Comment by maisano** [comment]
hi @ananescu. i'm a bit confused–what about it didn't work? you should still be able to do this, though you would have to override the `mapStyles` callback if you were using a prefix.

**Comment by spen** [comment]
@ananescu, that would look something like this:
```js
// You could inline this in the RouteTransition prop declaration, but I like to pull it out here.
const mapStyles = styles => ({
  transform: `translateY(${ styles.translateY }%)`,
});

<RouteTransition
  atEnter={{ translateY: 30 }}
  atLeave={{ translateY: -30 }}
  atActive={{ translateY: 0 }}
  mapStyles={ mapStyles }
>
  { children }
</RouteTransition>
```

The reason for doing this (correct me if I'am wrong @maisano ) is that unlike other styles that have a 1 to 1 mapping ( left: `left: value` , opacity: `opacity: value` ). 
`translateY`, `translateX` and some others do not. 
They map like so: 
 translateY: `transform: translateY( value );`
 translateX: `transform: translateX( value );`

**Comment by ananescu** [comment]
Hello, thank you for your answer. 
That is exactly what I did, but it didn't work. I will look into it more, though, maybe there's something I am missing.

**Comment by spen** [comment]
@ananescu That's odd 😕
Do other styles work? opacity for instance?
I ask because I had some general issues with getting the transitions to play as I'd have liked at first, my solution was to add `component={ false }` to the `<RouteTransition>` and consume the `style` prop in the child component itself.

**Comment by maisano** [comment]
@spen thanks for hopping in here to help :)

@ananescu what does your `<RouteTransition>` currently look like?
