### ISSUE TITLE
Please add support for Angular 4

### ISSUE THREAD

**Issue by bradleyboy** [maisano/react-router-transition#31]

**Comment by maisano** [comment]
@bradleyboy BANNED

**Comment by maisano** [comment]
@bradleyboy on second thought, i think we can make this work. just import the 45kb react runtime and write an angular thing that exposes a node that this mounts to and voila–best of both worlds!

sending you an invoice along with venmo money request for $200.

**Comment by jacobangel** [comment]
Actually it's "Angular" now. SO i think we should support 1, 2, and the briefly lived 3.
