### ISSUE TITLE
Doesn't work on IOS 8 or less

### ISSUE THREAD

**Issue by wmwwebworld** [maisano/react-router-transition#32]
It doesn't seem to work on IOS devices less than v9.
Is there any way to make it work, even if it is a hacky way?
I am aware of the fact that IOS 9 is the latest which supports CSS transitions.

**Comment by wmwwebworld** [comment]
Thanks @maisano! I will try to figure out an alternative way instead of transitions.

**Comment by maisano** [comment]
@wmwwebworld out of curiosity–did you try using `TransitionMotion` while adding style rules that contained `transition`s? if so, this would explain why it wouldn't work.

at any rate, let me know if you have any other questions!
