### ISSUE TITLE
dynamic routing/code splitting?

### ISSUE THREAD

**Issue by ngocketit** [maisano/react-router-transition#33]
Does it work with react-router [dynamic routing/code splitting](https://github.com/ReactTraining/react-router/blob/master/docs/guides/DynamicRouting.md)?

**Comment by maisano** [comment]
hi @ngocketit. there shouldn't be any reason it wouldn't work w/code-splitting, so long as the container has a `RouteTransition`. all this package does is provide animation hooks for mounting/unmounting components.

going to close this, feel free to reopen if you're unable to get it working.

**Comment by ngocketit** [comment]
Thanks @maisano! I tried and it indeed works. The only problem is that the new view usually comes blank for a while until the async data is loaded. This probably can be mitigated with a simple spinner.

**Comment by maisano** [comment]
@ngocketit great! glad that worked out. feel free to submit a pr with an example if you get it working and want to share that. no worries if not tho!
