### ISSUE TITLE
How to use Spring on Transform and mapstyle

### ISSUE THREAD

**Issue by cavaloni** [maisano/react-router-transition#35]
When applying `spring` to a value on transform it causes a constant looping error.  "[object Object]NaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNa…NNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaN"}

**Comment by maisano** [comment]
@cavaloni sounds like a bad config. can you paste what your usage looks like?

**Comment by maisano** [comment]
@cavaloni if i understand the problem, it sounds like you're using `spring` inside of `mapStyles`. `spring` is solely for defining a config struct that react-motion consumes and it shouldn't happen in `mapStyles`.
