### ISSUE TITLE
README links to not found page

### ISSUE THREAD

**Issue by TimMikeladze** [maisano/react-router-transition#37]
In the README

```
I strongly recommend looking at [React Router v4](https://react-router.now.sh/) and the authors' provided [animation example](https://react-router.now.sh/animated-transitions) before choosing this library.
```

The animation example no longer exists.

**Comment by maisano** [comment]
@TimMikeladze https://reacttraining.com/react-router/examples/animated-transitions

**Comment by maisano** [comment]
omg it updated again: https://reacttraining.com/react-router/web/example/animated-transitions
