### ISSUE TITLE
Online Demo please?

### ISSUE THREAD

**Issue by winkler1** [maisano/react-router-transition#4]
Sounds great -- would it be possible to get a demo online? Would like to add to react.rocks... thanks!

**Comment by maisano** [comment]
@winkler1 it should be easy enough to add a gh-pages branch since there's already a demos directory/build.

i'm currently on holiday so i won't be able to get to it for a week or so, if anyone else wants to take the lead.

**Comment by moaazsidat** [comment]
I might be able to help with this. Let me see if I can work on getting a PR for this. :smiley:

**Comment by maisano** [comment]
@winkler1 i've added a [link](http://maisano.github.io/react-router-transition/demos/#/fade) to the demos build in the latest readme.

**Comment by winkler1** [comment]
:+1:
