### ISSUE TITLE
Can you publish new version to npm?

### ISSUE THREAD

**Issue by Undeadlol1** [maisano/react-router-transition#44]
In order to suppress React's warnings regarding "PropTypes" and "createClass" code needs to be refactored.
Seems like commits are already being made but package version on npm is still outdated.
Maybe you forgot to publish it? ;)

**Comment by maisano** [comment]
@Undeadlol1 sure did–i've been p busy with work. just published an update.

**Comment by Undeadlol1** [comment]
Thank you.
Great work on the package btw, much appreciated.

**Comment by maisano** [comment]
no problem! thanks for the kind words :)
