### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by ebhoren** [maisano/react-router-transition#46]
I have this warning when running react-router-transition from create-react-app boilterplate.

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Could you consider replacing this by below in src/RouteTransition.jsx?
import React, { Component, PropTypes } from 'react'

to

import React, { Component } from 'react'
import PropTypes from 'prop-types'

Thanks in advance

**Comment by maisano** [comment]
@ebhoren this was also updated in the same pr: https://github.com/maisano/react-router-transition/pull/41
