### ISSUE TITLE
React.createClass is deprecated

### ISSUE THREAD

**Issue by ebhoren** [maisano/react-router-transition#47]
I had this warning when running react-router-transition in React 15.5.4.

Motion: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

Thanks

**Comment by bradleyboy** [comment]
+1

**Comment by maisano** [comment]
@ebhoren this is already done https://github.com/maisano/react-router-transition/pull/41
