### ISSUE TITLE
jsnext:main field

### ISSUE THREAD

**Issue by damianobarbati** [maisano/react-router-transition#56]
Please add `"jsnext:main": "src/RouteTransition.jsx"` into `package.json` to let devs transpile for their own environment.

**Comment by jacobangel** [comment]
[Many systems have deprecated jsnext:main](https://github.com/rollup/rollup/wiki/jsnext:main) in favor of the `module` field. It seems like we'd want to add both just to support people on older versions of both. Would you mind opening a pull request with this change?

**Comment by damianobarbati** [comment]
Done https://github.com/maisano/react-router-transition/pull/57
