### ISSUE TITLE
IE 11 not supported

### ISSUE THREAD

**Issue by MitchEnfield** [maisano/react-router-transition#67]
"Object doesn't support property or method 'find'"
Great library, but I really want my app to support IE.  Is there any way to make this happen?

**Comment by jacobangel** [comment]
You're likely missing modern polyfills on the Array object. You'll need to polyfill the find method on Arrays. You can do that in many ways in your project, one option is to run `npm install --save core-js` and add `require('core-js/es6/array');` to your App's entry point.

**Comment by maisano** [comment]
hi, hello, @MitchEnfield.

if you're conditionally polyfilling other things like `fetch`, `Promise`, etc., it should be fairly trivial even to write a `find` polyfill :)

alternatively, i would likely merge a PR that changed the `find` to a `forEach` for better browser support.

**Comment by MitchEnfield** [comment]
Thank you! That did the trick.
