### ISSUE TITLE
Supported on React Router v4 for React Native

### ISSUE THREAD

**Issue by tyhopp** [maisano/react-router-transition#69]
Thanks so much for creating this @maisano, I got it working on our React web app and it's awesome!

A question on support for React Router v4 for React Native - will this work in RN? I tried looking through the source for this project but I'm a bit new to this so I thought I'd ask directly here as well.

Getting this error currently: 
Unable to resolve module './factoryWithThrowingShims' ; doesn't exist

Tried `rm -rf node_modules && npm install` but no luck.

**Comment by maisano** [comment]
hi @tyhopp!

currently, react-router-transition is not compatible with react-native. that said, it _could_ be, though it would seemingly require a few small changes:

1. swapping the `react-router-dom` [package](https://github.com/maisano/react-router-transition/blob/e050e7bb51ab2d42467a2f7ef275dbfa57ed3507/package.json#L44) ([&](https://github.com/maisano/react-router-transition/blob/e050e7bb51ab2d42467a2f7ef275dbfa57ed3507/src/AnimatedRoute.js#L2-L3) [references](https://github.com/maisano/react-router-transition/blob/e050e7bb51ab2d42467a2f7ef275dbfa57ed3507/src/AnimatedSwitch.js#L2-L4)) in favor of `react-router`
2. removing any [DOM-specific code](https://github.com/maisano/react-router-transition/blob/e050e7bb51ab2d42467a2f7ef275dbfa57ed3507/src/RouteTransition.js#L85-L87) in favor of something more configurable.

after these things happen, it should be compatible with react-native, though i am curious how performant it would be.

---

that said, the error you're currently getting is referencing a file from the [prop-types package](https://github.com/facebook/prop-types/blob/master/factoryWithThrowingShims.js). it should get installed as a transitive dependency of this package–is it not in the `node_modules` directory of your project?

**Comment by tyhopp** [comment]
Thanks for the reply @maisano! I tried forking and translating the code to RN supported code, but in the end decided to just use the base [animated library](https://facebook.github.io/react-native/docs/animated.html) instead.

Also you're right, it was from prop-types! 

Cheers
