### ISSUE TITLE
Does not seem to work with flex layout

### ISSUE THREAD

**Issue by pke** [maisano/react-router-transition#7]
Thanks for the component! I'd like to use them in my flexbox based app.
All my divs are styled as relative and with flex layout

```
div, span {
  box-sizing: border-box;
  position: relative;
  border: 0 solid black;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  align-items: stretch;
  justify-content: flex-start;
  flex-shrink: 0;
}
```

And this is my markup that renders the `children`

```
<div style={{height:"100vh", width: "100vw"}}>
  <div style={STYLES.appbar}></div>
  <div style={STYLES.content}>
    {children}
  </div>
  <NavBar style={STYLES.navbar}/>
</div>

const STYLES = {
  appbar: {
    flex: "none"
  },

  content: {
    flex: 1
  },

  navbar: {
    flex: "none"
  },
}
```

Wrapping `children` into `ReactRouterTransition` displays the old content for a moment together with the new content but then the new content jumps up to the page start (when the previous page has been removed).

Any ideas how to get this Component to work with flexbox?

**Comment by fredrik-sogaard** [comment]
I'm wondering the same. Any luck finding a solution, @pke ?

**Comment by maisano** [comment]
i've not tried to do this with flexbox, so i'm not certain, but in order for these particular transitions to work, the routes need to be absolutely positioned.

**Comment by jasan-s** [comment]
same issue here, any solutions?

**Comment by mr-e-** [comment]
same issue here:(

**Comment by cristiandley** [comment]
Same issue here :( React Router 4 + Grommet

**Comment by houfeng0923** [comment]
+1

**Comment by damianobarbati** [comment]
I mean: it's 2017, give a look to the browser share stats... who's not using flexbox today?
+1

**Comment by maisano** [comment]
this lib does work with flexbox. but like any animation library, you have to keep layout constraints in mind when designing your animations. closing as these comments are not helpful.

**Comment by damianobarbati** [comment]
@maisano sorry if I looked harsh I really didn't mean that (it was just an aside consideration about browser usage)!
Great job with this repo and thanks for the `presets`, those look like "batteries included" to me xD

All we have to remember is to absolutely position the container hosting the animated elements, clearly stated in the README and in other issues too.

Here a quick working reference that could help someone:
```
import React from 'react';
import { ConnectedRouter } from 'react-router-redux';
import { Switch, Route, Redirect } from 'react-router-dom';
import createHistory from 'history/createBrowserHistory';
import { RouteTransition, presets } from 'react-router-transition';

import { Nav, Component1, Component2 } from 'your-stuff-bro';

export const history = createHistory({ basename: '/' });

export default class Router extends React.Component {
    render() {
        return (
            <ConnectedRouter history={history}>
                <div id="container">
                    <Nav />
                    <Route render={ ({ location, history, match }) => {
                        const { action } = history;
                        const animation = action === 'PUSH' ? presets.slideLeft : presets.slideRight;

                        return (
                            <RouteTransition pathname={location.pathname} {...animation}>
                                <div style={{ position: 'absolute' }}>
                                    <Switch>
                                        <Route exact path="/component1" component={Component1} />
                                        <Route exact path="/component2" component={Component2} />
                                    </Switch>
                                </div>
                            </RouteTransition>
                        );
                    }} />
                </div>
            </ConnectedRouter>
        );
    }
}
```
