### ISSUE TITLE
Wrong import in demo

### ISSUE THREAD

**Issue by danedavid** [maisano/react-router-transition#73]
In the demo for `AnimatedSwitch`, I found the following line:

**AnimatedSwitchDemo.js**:
`import { spring, AnimatedRoute } from 'react-router-transition';`

..but have used:
```
<AnimatedSwitch
    atEnter={bounceTransition.atEnter}
    atLeave={bounceTransition.atLeave}
    atActive={bounceTransition.atActive}
    mapStyles={mapStyles}
    className="route-wrapper"
  >
```
.. and `AnimatedRoute` seems to be not used anywhere.

**Comment by maisano** [comment]
good catch–feel free to PR!
