### ISSUE TITLE
How to access your presets?

### ISSUE THREAD

**Issue by kennetpostigo** [maisano/react-router-transition#8]
Hello, I want to access your presets for fade, slideLeft, etc. How would I access them from the app to set the atEnter atLeave atActive? Also is react-motion accessible straight from `react-router-transition` in order to add custom transitions without having to install react-motion from my project?

**Comment by maisano** [comment]
the `presets` should be accessible from the top-level module, e.g.

```js
import { presets } from 'react-router-transition';
```

and while `react-motion` is a dependency of this project, we don't export it anywhere. if you wanted to set different attributes for custom transitions, you don't need to use `react-motion` directly–you would just define the properties in the `atEnter`, `atLeave`, etc.

**Comment by kennetpostigo** [comment]
@maisano thank you for the reply, How to I activate the presets in the transition component? So far I have `atEnter`, `atLeave`, `atActive, not sure how to split the preset up to put into these props. I tried looking at the demo and I couldn't quite understand it.

**Comment by jacobangel** [comment]
You can add them by object spread, or manually: 

```js
import { presets, RouteTransition } from 'react-router-transition';

<RouteTransition {...preset.slideRight}>  .. </RouteTransition>

// OR 

<RouteTransition
  atEnter={preset.slideRight.atEnter} 
  atLeave={preset.slideRight.atLeave} 
  atActive={preset.slideRight.atActive} 
>  .. </RouteTransition>
```

**Comment by kennetpostigo** [comment]
@jacobangel Thank you!

**Comment by uxlayouts** [comment]
I'm getting: 'preset' is not defined  no-undef
Also don't you still need path=""?

**Comment by maisano** [comment]
@uxlayouts have you imported them from the `react-router-transition` package? and yes, on the latest version you still need a `pathname` prop–this will change very soon however.

**Comment by ADavidLiu** [comment]
Is this still valid? I'm getting `Attempted import error: 'presets' is not exported from 'react-router-transition'.`

How can I access these so I don't have to create custom style animations?

**Comment by maisano** [comment]
@ADavidLiu – it depends on which version of this library you're using. The most recent version of the API removed all presets from the library.
