### ISSUE TITLE
Different styles at mount/unmount

### ISSUE THREAD

**Issue by ilya404** [maisano/react-router-transition#81]
Hi! Thanks for this plugin!

I have tried AnimatedSwitch from the example, and it works fine with:
atEnter={{opacity: 0}}
atLeave={{ opacity: 0}}
 atActive={{ opacity: 1}}

How exactly do I pass some other styles? 
Let's say atEnter={{opacity: 0, color: 'red'}} does not work. What am I missing or doing wrong?

**Comment by maisano** [comment]
hi @ilya404! the objects that get passed into `atEnter`, `atLeave` and `atActive` are values that are to be interpolated by react-motion–thus the only valid value types are numbers. you should be able to make the color red inside of your component, perhaps based on some other piece of state.
