### ISSUE TITLE
Unable to combine AnimatedSwitch and AnimatedRoute

### ISSUE THREAD

**Issue by Olliebaba** [maisano/react-router-transition#82]
I am trying to place an AnimatedRoute within an AnimatedSwitch but the AnimatedRoute's styles are completely ignored. In my application I have a few different transitions but they aren't all the same at a specified level. 

I was hoping to use an AnimatedSwitch to handle the most common transition and to insert an AnimatedRoute within for the custom transition. Is this possible? I have tried to implement the combination in my own application as well as in the demo provided and no dice.

**Comment by maisano** [comment]
hi @olliebaba!

unfortunately the two do not compose well together. `AnimatedRoute` is for situations when you _always_ have a `Route` mounted (whether it is rendering is another story), and this is antithetical to the way that `Switch` works (by actually only mounting the first sequential matching child route).

that said, i wouldn't recommend trying to combine the two–perhaps i could have spelled that out better in the documentation.

**Comment by Olliebaba** [comment]
@maisano - Thanks for the input!
