### ISSUE TITLE
Parceljs cannot compile

### ISSUE THREAD

**Issue by houlonglong** [maisano/react-router-transition#84]
Server running at http://localhost:1234
🚨  /Volumes/HDD/project/projects/lawson_event_frontend/node_modules/react-router-transition/lib/react-router-transition.js:117:27: Cannot resolve dependency '
   module.exports = require('./factoryWithThrowingShims')();
      |                            ^
}

**Comment by maisano** [comment]
hi @houlonglong! that module, `factoryWithThrowingShims` is from the `prop-types` package [[link](https://github.com/facebook/prop-types/blob/master/factoryWithThrowingShims.js)]. do you have that installed? if you ran `npm install react-router-transition`, you should have it as a transitive dependency.

**Comment by bsonntag** [comment]
I'm having a similar error:

`Error: Cannot find module './factoryWithThrowingShims' from '/path/to/project/node_modules/react-router-transition/lib'`

I have `prop-types` installed.

**Comment by bsonntag** [comment]
I fixed this by setting an alias of `react-router-transition` to `react-router-transition/lib/index.js` in my babel config.

I think this happened to me because I'm using browserify and it probably tried to use the `main` entry defined in the package.json, which points to "lib/react-router-transition.js".

**Comment by maisano** [comment]
@houlonglong @bsonntag – i just published 1.1.3 which should fix this issue. thanks for pointing it out!

**Comment by bsonntag** [comment]
@maisano I can confirm that it's now working. Thanks!
