### ISSUE TITLE
How about adding didLeave callback to RouteTransition component?

### ISSUE THREAD

**Issue by wgundamj44** [maisano/react-router-transition#86]
I have a use case where some actions need to be triggered when route transition is done. 

However, current implementation doesn't support passing `didLeave`  callback to underlying `TransitionMotion`.  So how about add `didLeave` as a new property to `RouteTranstion` component?

**Comment by maisano** [comment]
hi @wgundamj44! does a downstream `componentWillUnmount` not work for that use case?

either way i could see this being useful. would you like to give the implementation a go?

**Comment by maisano** [comment]
@wgundamj44 just published the version `1.2.0`, which contains your changes. thanks again for the PR!
