### ISSUE TITLE
Code Example for Nested Transition?

### ISSUE THREAD

**Issue by joncursi** [maisano/react-router-transition#9]
I'm trying to configure a nested transition with a few rules.
- At the root of my app, a `RouteTransition` that fade transitions among it's child peers, and slide left transitions to a grandchild page.
- One layer down, on a grandchild page, a new `RouteTransition` (?) that has different transition behavior (i.e. no transition among its peers and a slide right to go back up to it's parent).
## The Issue
- The root transition's `pathname` prop can't be as simple as `this.props.location.pathname` because that will interfere with grandchild rendering and transitions: URL change causes each children to fully re-mount, which disrupts the nested transition.

Can you help me understand how to set this up? Is it possible to prevent peer children from totally re-mounting (they have basically 50% shared components)? I think a code example would be really helpful. Thanks!

**Comment by joncursi** [comment]
Here's a graphic of what I'm after:

![img_0083](https://cloud.githubusercontent.com/assets/4974609/15900572/efe46dfe-2d6d-11e6-9666-0c382b93bb64.JPG)

**Comment by maisano** [comment]
@joncursi thanks for opening a ticket–it's a big oversight on my part to not have included a demo or example of nested transitions.

as it stands, nested transitions are somewhat limited. each `RouteTransition` works only to animate in it's children. the way i've done it in the past is to pass in a slice of the pathname, something that represents _the_ animatable route in question, e.g.

```jsx
// given these routes
<Route path="/" component={App}>
  <Route path="one" component={One}>
    <Route path="a" component={A} />
    <Route path="b" component={B} />
  </Route>
  <Route path="two" component={Two}>
    <Route path="a" component={A} />
    <Route path="b" component={B} />
  </Route>
</Route>

// where `One` or `Two` looks something like
const OneOrTwo = (props) => {
  const pathname = props.location.pathname;
  const routePath = props.route.path;

  return (
    <RouteTransition
      pathname={pathname.slice(0, pathname.indexOf(routePath) + routePath.length)}
      atEnter={{ atEnter }}
      atLeave={{ atLeave }}
      atActive={{ atActive }}
    >
      {props.children}
    </RouteTransition>
  );
};

// and `A` or `B` looks like
const AOrB = (props) => {
  return (
    <RouteTransition
      pathname={props.pathname}
      atEnter={{ atEnter }}
      atLeave={{ atLeave }}
      atActive={{ atActive }}
    >
      {props.children}
    </RouteTransition>
  );
};
```

if i understand correctly, what you want isn't currently possible without using `react-motion` directly. there might be a way to do some pathname comparisons and choose a transition preset dynamically? out of curiosity, were you able to have the grandchild transition when going back to the child (e.g., `/one/a` -> `/one`)?

**Comment by joncursi** [comment]
@maisano thanks for your quick response! I will try fiddling with slice on the URL to see if that's an option. My biggest issue in this routing scheme is the forced re-mounting of grandchildren due to key change induced by URL change, so it sounds like this might help.

Here's what I'm currently doing. When the user navigates around the app, I store a _selective_ history of routes they visit in an immutable List that lives in a redux store -- _only unshifting new values when a change in tree depth is detected_. Default list state:

```jsx
[]
```

List state after the user has navigated around:

```jsx
[
  '/one/a', // two levels down (current route)
  '/one' ,  // back down a level (previous route)
  '/',      // back up a level
  '/one' ,  // user went one level down
  '/',      // route the user accessed the app with; happens to be base level
]
```

The data in this array is used to conditionally show a back button on grandchild routes that navigates up the tree to a child route. Basically, if `history[1]` exists (the previous route), I know that they got to this route from either a parent or a child. (I am aware that react router stores a history array of it's own, but that history contains everything and also [contains non-app history data](https://github.com/reactjs/react-router/issues/1874), and thus does not work well with conditional back button usage, so I opted to track my own selective history).

On these conditional buttons, I am using this history array with `Link` state to dictate the transition type.

For buttons that navigate between peers:

```jsx
<Link
  to={{
    pathname: destination.pathname,
    state: {
      transition: 'fade',
    },
  }}
/>
```

For back buttons that navigate _up_ the component tree:

```jsx
<Link
  to={{
    pathname: destination.pathname,
    state: {
      transition: 'slideRight',
    },
  }}
/>
```

For buttons that navigate _down_ the component tree:

```jsx
<Link
  to={{
    pathname: destination.pathname,
    state: {
      transition: 'slideLeft',
    },
  }}
/>
```

I only have a single `RouteTransition` that lives on my main application layout, and it reads the transition style to use from `Link` state when the user clicks a Link. Like this:

```jsx

    import * as transitions from '../../helpers/transitions.js'; // react-motion presets

    ...

    let transition;
    if (routerState.get('locationBeforeTransitions')) { // if a transition has been set via Link state, use it
      transition = transitions[`${routerState.get('locationBeforeTransitions').get('transition')}`];
    } else { // otherwise, fallback to no transition
      transition = transitions.noTransition;
    }

    ...

    <RouteTransition
      className="transition-wrapper"
      pathname={location.pathname}
      {...transition}
    >
      { children }
    </RouteTransition>
```

With this setup, every route is transition-able, and the transition style is set on `Link` click and fed into a single `RouteTransition` that sits at the top level of the app. However, by using `location.pathname` as the key, I run into the issue of complete component re-mounting as key change this high in the component tree will force a complete re-render of everything beneath it.

Does that make sense? Do you have any feedback on this approach? It's definitely not the cleanest, and probably will not scale too far, but it's sort of working, at least for now.
