### ISSUE TITLE
Possible to use both AnimatedSwitch and AnimatedRoute w/o them breaking the other?

### ISSUE THREAD

**Issue by corysimmons** [maisano/react-router-transition#91]
I'm trying to do app-like horizontal slides from page-to-page, and I want to have a Sidebar button.

I can get AnimatedSwitch working for pages, but when I try to add AnimatedRoute, it loads the sidebar, but the page under the sidebar is lost and it 404's.

I can probably just do the Sidebar as a normal component for now but I'm curious how react-router-transition approaches the problem of needing to do one-off routes without the current page dying in the Switch.

**Comment by maisano** [comment]
hi @corysimmons! unforunately the scope of `AnimatedRoute` is pretty limited. if i understand correctly, you'd have to pull the `AnimatedRoute` from outside of the `AnimatedSwitch` tree and render it somewhere adjacent or above in scope.

hopefully that helps somewhat!

**Comment by corysimmons** [comment]
Thanks for the insight
