### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by TanKucukhas** [maisano/react-router-transition#96]
I wanted to use the plugin on my project but couldn't find ``@types/react-router-transition``. Is there a workaround or any plans to add support for TypeScript? Thanks in advance.

**Comment by TanKucukhas** [comment]
Here is a workaround I've found to suppress typescript until we have a @types file.

``declare function require(moduleName: string): any;``
``const AnimatedRoute = require('react-router-transition').AnimatedRoute;``

**Comment by quirimmo** [comment]
You could even do: 

`import * as ReactRouterTransition from 'react-router-transition';`

And then use it as object: `ReactRouterTransition .AnimatedSwitch` for example

**Comment by itzsaga** [comment]
This works too `declare module "react-router-transition";`

**Comment by jakelauer** [comment]
I think this covers it:

```
declare module "react-router-transition"
{
	import {RouteProps} from "react-router";

	interface AnimatedSwitchProps
	{
		atEnter: React.CSSProperties;
		atLeave: React.CSSProperties;
		atActive: React.CSSProperties;
		didLeave?: (style: React.CSSProperties) => void;
		className?: HTMLDivElement;
		wrapperComponent?: keyof HTMLElementTagNameMap;
		mapStyles?: (styles: React.CSSProperties) => React.CSSProperties;
		runOnMount?: boolean;
		children: React.ReactNode;
	}

	interface AnimatedRouteProps extends RouteProps
	{}


	export const AnimatedSwitch: React.ComponentClass<AnimatedSwitchProps>;
	export const AnimatedRoute: React.ComponentClass<AnimatedRouteProps>;
	export const RouteTransition: React.ComponentClass<AnimatedSwitchProps>;
}
```

**Comment by jakelauer** [comment]
Added a PR: https://github.com/maisano/react-router-transition/pull/115

**Comment by maisano** [comment]
There aren't any plans to rebuild this library in TypeScript. That said, if someone wants to PR the types to DefinitelyTyped, I think that should help with this. I don't use TypeScript with React personally, so I'm not much help here–sorry y'all!

**Comment by b-d-m-p** [comment]
> I think this covers it:
> 
> ```
> declare module "react-router-transition"
> {
> 	import {RouteProps} from "react-router";
> 
> 	interface AnimatedSwitchProps
> 	{
> 		atEnter: React.CSSProperties;
> 		atLeave: React.CSSProperties;
> 		atActive: React.CSSProperties;
> 		didLeave?: (style: React.CSSProperties) => void;
> 		className?: HTMLDivElement;
> 		wrapperComponent?: keyof HTMLElementTagNameMap;
> 		mapStyles?: (styles: React.CSSProperties) => React.CSSProperties;
> 		runOnMount?: boolean;
> 		children: React.ReactNode;
> 	}
> 
> 	interface AnimatedRouteProps extends RouteProps
> 	{}
> 
> 
> 	export const AnimatedSwitch: React.ComponentClass<AnimatedSwitchProps>;
> 	export const AnimatedRoute: React.ComponentClass<AnimatedRouteProps>;
> 	export const RouteTransition: React.ComponentClass<AnimatedSwitchProps>;
> }
> ```

For anyone who is not as familiar with this, make a `@types` directory in your `src` directory and put the above code in a `react-router-transition.d.ts` file and that will get you going.
