### ISSUE TITLE
Lag when transition to another page

### ISSUE THREAD

**Issue by aibrahim3546** [maisano/react-router-transition#97]
when the page changes the transitions become laggy, I found out that it is laggy because of an API call. The transition is getting blocked when calling the API. How do I avoid this problem?

**Comment by maisano** [comment]
hi @aibrahim3546! this is something that will have a clearer path forward in the future, when async react is a reality. in the meantime, i'm not certain how or when you're making an api call, but deferring it or prefetching it should work well enough. if you're fetching in the `componentDidMount` of a transitioning component, i would expect there to be a lag. maybe give deferring the call or prefetching it a try.

**Comment by aibrahim3546** [comment]
Thank you for the response, So I guess the only way is to delay the API call.

**Comment by maisano** [comment]
@aibrahim3546 no problem–i might give `requestIdleCallback` a shot here, if you have it shimmed.
